### ISSUE TITLE
В чем мем?

### ISSUE THREAD

**Issue by s3ponia** [UnickSoft/GraphOffline#1]
Зачем писать свою реализацию строки? Зачем виртуальное наследование? 
![image](https://user-images.githubusercontent.com/29208820/83815755-99f79b80-a6c9-11ea-9286-e2757c3beaf0.png)

![image](https://user-images.githubusercontent.com/29208820/83815710-7fbdbd80-a6c9-11ea-99d7-673b7f42cf49.png)

**Comment by UnickSoft** [comment]
Здравствуйте.
Собственная реализация строки, сейчас не используется. Пока не удалена из проекта.

Виртуа́льное насле́дование нужен для решения некоторых проблем, порождаемых наличием возможности множественного наследования (особенно «ромбовидного наследования»), путём разрешения неоднозначности того, методы которого из суперклассов (непосредственных классов-предков) необходимо использовать.

**Comment by s3ponia** [comment]
Просто я неочень понимаю зачем такая раздутая иерархия классов с кучей интерфейсов. Например тот же скрин где интерфейс специализируется просто чтобы возвращать инт.

**Comment by UnickSoft** [comment]
Структура с интерфейсами была использована с заделом на будущее, чтобы можно было использовать утилиту как внешнюю dll библиотеку. Но пока это не реализовано. 
Интерфейс IMultiGraphInt выделен в отдельный интерфейс, т.к. граф может иметь веса с плавающий точкой и это уже будет интерфейс IMultiGraphFloat. Можно было везде использовать float, но работа с int быстрее чем с float. Поэтому пришлось разделить.
Также различаются интерфейсы для обычного графа и для мутльтиграфа. Т.к. они имеют немного другие методы для получения информации о дугах и как правило алгоритмы для них буду работать немного по разному.
